version: "3.8"

volumes:
  kafka-data:
    driver: local

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'
    restart: unless-stopped
    environment:
      KAFKA_BROKER_ID: 1
    hostname: zookeeper
  kafka:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    container_name: kafka
    hostname: kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: "/kafka/kafka-logs-ant-kafka"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka-data/:/kafka
    depends_on:
      - zookeeper
    restart: unless-stopped
